@echo off
echo Checking for existing ADB connection...
adb devices | findstr /i "device" > nul
if %errorlevel%==0 (
    echo Device already connected. Skipping reconnection...
) else (
    echo No devices connected. Attempting wireless connection setup...

    echo Disconnecting old ADB connections...
    adb disconnect

    echo Please connect your Android via USB for setup...
    pause

    echo Switching to TCP/IP mode...
    adb tcpip 5555

    echo Getting device IP address...
    FOR /F "tokens=2" %%G IN ('adb shell ip addr show wlan0 ^| find "inet " ') DO set ipfull=%%G
    FOR /F "tokens=1 delims=/" %%G IN ("%ipfull%") DO set ip=%%G

    echo IP address detected: %ip%
    echo Connecting to device over Wi-Fi...
    adb connect %ip%
)
